### ISSUE TITLE
This does not work with the Bloqs add-on

### ISSUE THREAD

**Issue by sparkison** [ThorntonStuart/SimpleCloner#1]
Would be awesome if this could be updated to work with the [Bloqs](https://devot-ee.com/add-ons/bloqs-blocks-for-ee3) add-on! If you need any help testing with this I would be happy to assist.

**Comment by ThorntonStuart** [comment]
Hey there! Do you get any error messages? I don't have the add-on installed so help with testing would be much appreciated. My immediate suspicion is that this could be fieldtype related.

**Comment by sparkison** [comment]
Sorry for the delay! But, I think you're right about it being fieldtype related. No obvious errors are reported. I'll take a look at the php logs and see if I can find anything.

In the meantime, I'm sure [Q-Digital](https://www.qdigitalstudio.com/contact) would be willing to give you a license to try the plugin out for development

**Comment by ThorntonStuart** [comment]
Hi again. I got a copy of the latest version of Bloqs (3.0.15) and can't seem to replicate any issues. Can I ask which version of EE3 you are running and which version of the Bloqs add-on you're using? I'm guessing there is just no duplicate entry when you are redirected to the Channel Entries view?

**Comment by kchatel** [comment]
Has there been any update regarding this issue. It does create a clone of the entry but all the bloqs assigned to the original do not get cloned over.

**Comment by omg-monkee** [comment]
I had trouble getting this plugin to work with both Bloqs and Grid on 3.4.5. I would clone an entry but all of the Bloqs and Grid fields would be empty. Bloqs is basically a Grid "replacement" (which is the main reason why you can't put a Grid field inside of Bloqs) and utilizes the Grid libraries, so the issue may be hand in hand. I'm curious if anyone who has experience the Bloqs problem also experiences it with Grid.

**Comment by kchatel** [comment]
Actually my colleague William forked this repo and has made those changes. https://github.com/williamsears/SimpleCloner/ Just missing the support for relationships inside of Bloqs and Grids
